### ISSUE TITLE
Can't run simantha

### ISSUE THREAD

**Issue by Lucheti** [m-hoff/simantha#2]
when trying the example on the Readme.md i get:

`Traceback (most recent call last):
  File "SingleMachine.py", line 1, in <module>
    from simantha import Source, Machine, Sink, System
  File "/Users/lucas.garcia/Library/Python/3.8/lib/python/site-packages/simantha/__init__.py", line 1, in <module>
    from .System import System
  File "/Users/lucas.garcia/Library/Python/3.8/lib/python/site-packages/simantha/System.py", line 9, in <module>
    from .Source import Source
  File "/Users/lucas.garcia/Library/Python/3.8/lib/python/site-packages/simantha/Source.py", line 3, in <module>
    from .Machine import Machine
  File "/Users/lucas.garcia/Library/Python/3.8/lib/python/site-packages/simantha/Machine.py", line 266
    <<<<<<< HEAD`

**Comment by m-hoff** [comment]
It should be fixed now. Try uninstalling and reinstalling simantha and see if the example works.
